Julia 1.6:
  image: julia:1.6
  script: julia --project='@.' -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)'
  coverage: /Test Coverage (\d+\.\d+%)/
  after_script:
    - julia -e 'using Printf; using Pkg; Pkg.add("Coverage"); using Coverage; c, t = get_summary(process_folder()); @printf "Test Coverage %.2f%%\n" 100c/t'
pages:
  image: julia:1.6
  stage: deploy
  script:
    - julia --project=docs -e '
      using Pkg;
      Pkg.develop(PackageSpec(path=pwd()));
      Pkg.instantiate();
      include("docs/makedocs.jl");'
    - mkdir -p public
    - mv docs/build public
  artifacts:
    paths:
      - public
  only:
    - master
