name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['1', 'nightly']
        arch: [x64]
        os: [ubuntu-latest]
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        #exclude:
        #  - os: macOS-latest
        #    julia-arch: x86

    steps:
      - uses: actions/checkout@v4

      # Set up Python and install Matplotlib
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Matplotlib
        run: pip install matplotlib

      # Continue with existing Julia setup
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-artifacts-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-artifacts-

      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ""

      - uses: julia-actions/julia-runtest@v1
        env:
          PYTHON: ""
